---
- name: Create deploy user
  become: yes
  user:
    name: deploy
    comment: Application Deployment
    shell: /bin/bash
    groups:
      - adm
      - sudo
      - systemd-journal

- name: Add the main SSH public key for the deploy user
  become: yes
  authorized_key:
    user: deploy
    key: "{{ lookup('file', 'roles/machine/files/authorized_keys') }}"

- name: Add the deploy SSH public key for the deploy user
  become: yes
  authorized_key:
    user: deploy
    key: "{{ lookup('file', 'authorized_keys') }}"

- name: Copy OpenSSH client configuration for the deploy user
  become: yes
  copy:
    src: roles/machine/files/ssh_config
    dest: /home/deploy/.ssh/config
    owner: deploy
    group: deploy
    backup: yes

- name: Copy the bash configuration file for the deploy user
  become: yes
  copy:
    src: roles/machine/files/bashrc
    dest: /home/deploy/.bashrc
    owner: deploy
    group: deploy
    backup: yes

- name: Copy the profile for the deploy user
  become: yes
  copy:
    src: roles/machine/files/profile
    dest: /home/deploy/.profile
    owner: deploy
    group: deploy
    backup: yes
