---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine
    - deploy

- name: Desktop machine configuration
  hosts: scrap.quinn.tk

  roles:
    - dot

- name: Core server configuration
  hosts: scrap.quinn.tk, len.quinn.tk

  roles:
    - ftp
    - nameserver

- name: Application server configuration
  hosts: scrap.quinn.tk, len.quinn.tk, turn.personaltelco.net

  roles:
    - email
    - webserver
    - build
    - rails

- name: Extranet configuration
  hosts: len.quinn.tk

  roles:
    - xmit

- name: Intranet configuration
  hosts: scrap.quinn.tk

  roles:
    - intranet
    - qa
    - redmine
