---
- name: Standard machine configuration
  hosts: all

  roles:
    - machine

- name: Webserver configuration
  hosts: scrap.quinn.tk, len.quinn.tk

  roles:
    - webserver

- name: Creature comforts
  hosts: scrap.quinn.tk

  roles:
    - comfort
