---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine
    - nameserver
    - email

- name: Webserver configuration
  hosts: scrap, len

  roles:
    - build
    - rails
    - webserver
    - palkan.phantomjs

- name: Mailing lists
  hosts: len

  roles:
    - listserv

- name: Creature comforts
  hosts: pi, scrap

  roles:
    - comfort

- name: Intranet configuration
  hosts: scrap

  roles:
    - intranet

- name: quinn.tk
  hosts: scrap, len

  tasks:
  - name: Create directory
    become: yes
    file:
      path: /srv/www/quinn.tk
      state: directory
      mode: 0755
      owner: '{{ ansible_user_uid }}'
      group: '{{ ansible_user_gid }}'

  - name: Sync site
    git:
      repo: scrap.quinn.tk:/srv/data/git/quinn.tk.git
      dest: /srv/www/quinn.tk
      version: master

- name: basslin.es
  hosts: len

  tasks:
  - name: Create directory
    become: yes
    file:
      path: /srv/www/basslin.es
      state: directory
      mode: 0755
      owner: '{{ ansible_user_uid }}'
      group: '{{ ansible_user_gid }}'

  - name: Sync site
    git:
      repo: scrap.quinn.tk:/srv/data/git/basslin.es.git
      dest: /srv/www/basslin.es
      version: master
