---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine
    - deploy

- name: Desktop machine configuration
  hosts: scrap.qtk.io

  roles:
    - dot

- name: Core server configuration
  hosts: scrap.qtk.io, len.qtk.io

  roles:
    - ftp
    - nameserver

- name: Application server configuration
  hosts: scrap.qtk.io, len.qtk.io

  roles:
    - email
    - webserver
    - build
    - rails

- name: Intranet configuration
  hosts: scrap.qtk.io

  roles:
    - intranet
    - qa
    - redmine
    - xmit
