---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine

- name: Nameserver configuration
  hosts: scrap.quinn.tk, len.quinn.tk

  roles:
    - nameserver

- name: Application server configuration
  hosts: scrap.quinn.tk, len.quinn.tk

  roles:
    - email
    - webserver
    - build
    - ftp
    - rails
    - palkan.phantomjs

- name: Intranet configuration
  hosts: scrap.quinn.tk

  roles:
    - comfort
    - dot
    - intranet
    - qa
    - redmine
