---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine
    - nameserver
    - email

- name: Webserver configuration
  hosts: scrap, len

  roles:
    - build
    - rails
    - webserver
    - palkan.phantomjs

- name: Creature comforts
  hosts: scrap

  roles:
    - comfort

- name: quinn.tk
  hosts: scrap

  tasks:
  - name: Sync site
    git:
      repo: scrap.quinn.tk:/srv/data/git/quinn.tk.git
      dest: /srv/www/quinn.tk
      version: master

  roles:
    - intranet

- name: basslin.es
  hosts: len

  tasks:
  - name: Sync site
    git:
      repo: scrap.quinn.tk:/srv/data/git/basslin.es.git
      dest: /srv/www/basslin.es
      version: master
