---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine

- name: Core server configuration
  hosts: scrap.quinn.tk, len.quinn.tk

  roles:
    - ftp
    - nameserver

- name: Application server configuration
  hosts: scrap.quinn.tk, len.quinn.tk, turn.personaltelco.net

  roles:
    - email
    - webserver
    - build
    - rails
    - palkan.phantomjs

- name: Intranet configuration
  hosts: scrap.quinn.tk

  roles:
    - comfort
    - dot
    - intranet
    - qa
    - redmine
