---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine
    - nameserver

- name: Application server configuration
  hosts: scrap, len

  roles:
    - email
    - webserver
    - build
    - ftp
    - rails
    - palkan.phantomjs

- name: Organization services
  hosts: len

  roles:
    - listserv
    - social

- name: Creature comforts
  hosts: pi, scrap

  roles:
    - comfort

- name: Intranet configuration
  hosts: scrap

  roles:
    - dot
    - intranet
    - qa
    - redmine
