---
- name: Standard machine configuration
  hosts: servers

  roles:
    - machine
    - deploy

- name: Server configuration
  hosts: scrap, len

  roles:
    - nameserver
    - email
    - webserver
    - build
    - rails

- name: Intranet configuration
  hosts: scrap

  roles:
    - dot
    - intranet
    - qa
    - redmine
    - xmit
