source 'http://rubygems.org'

gem 'rails'

gem 'capistrano'
gem 'haml'
gem 'jquery-rails'
gem 'mysql2'

group :assets do
  gem 'coffee-rails'
  gem 'sass-rails'
  gem 'uglifier'
end

group :development, :test do
  gem 'autotest-rails'
  gem 'rspec-rails'
  gem 'simplecov', :require => false
end
