# -*- shell-script -*-
# ~/.bashrc: executed by bash(1) for non-login shells.

export PATH="$HOME/.rbenv/bin:/usr/local/sbin:$PATH"
eval "$(rbenv init -)"

# Set prompt and window title.
PS1='\u@\h:\w\$ '
case "$TERM" in
xterm*|rxvt*)
    PS1="\\[\\e]0;\\u@\\h:\\w\\a\\]$PS1"
    ;;
*)
    ;;
esac
