---
- name: Install rails application server packages
  become: yes
  apt:
    state: present
    name:
      - postgresql
      - python-psycopg2
      - redis-server

- name: Create root user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: root
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER

- name: Create keegan user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: keegan
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER

- name: Copy database backup script
  become: yes
  copy:
    src: pg_backup.sh
    dest: /usr/local/sbin
    owner: root
    group: root
    mode: 0755

- name: Schedule database backup
  become: yes
  cron:
    name: database backup
    cron_file: pg_backup
    user: root
    job: /usr/local/sbin/pg_backup.sh
    minute: 0
    hour: 1

- name: Create deploy user
  become: yes
  user:
    name: deploy
    comment: Application Deployment
    shell: /bin/bash
    groups: sudo

- name: Copy the SSH public key for the deploy user
  become: yes
  authorized_key:
    user: deploy
    key: "{{ lookup('file', 'roles/dot/files/authorized_keys') }}"

- name: Copy Rails configuration
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/rails/'
    dest: /etc/rails
    owner: deploy
    group: deploy
    mode: 0600

- name: Install rbenv for the deploy user
  become: yes
  become_user: deploy
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/deploy/.rbenv
    version: master

- name: Install rbenv-sudo for the deploy user
  become: yes
  become_user: deploy
  git:
    repo: https://github.com/dcarley/rbenv-sudo.git
    dest: /home/deploy/.rbenv/plugins/rbenv-sudo
    version: master

- name: Install ruby-build for the deploy user
  become: yes
  become_user: deploy
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/deploy/.rbenv/plugins/ruby-build
    version: master

- name: Copy the bashrc for the deploy user
  become: yes
  become_user: deploy
  copy: src=bashrc dest=/home/deploy/.bashrc

- name: Copy the profile for the deploy user
  become: yes
  become_user: deploy
  copy: src=profile dest=/home/deploy/.profile

- name: Install Ruby 2.6.2 for the deploy user
  become: yes
  become_user: deploy
  shell: /home/deploy/.rbenv/bin/rbenv install -s 2.6.2
  args:
    creates: /home/deploy/.rbenv/versions/2.6.2

- name: Install Bundler for the deploy user
  become: yes
  become_user: deploy
  shell: RBENV_VERSION=2.6.2 /home/deploy/.rbenv/shims/gem install bundler
  args:
    creates: /home/deploy/.rbenv/versions/2.6.2/bin/bundler

- name: Install Foreman for the deploy user
  become: yes
  become_user: deploy
  shell: RBENV_VERSION=2.6.2 /home/deploy/.rbenv/shims/gem install foreman
  args:
    creates: /home/deploy/.rbenv/versions/2.6.2/bin/foreman

- name: Create /srv/rails
  become: yes
  file:
    path: /srv/rails
    state: directory
    mode: 0755
    owner: deploy
    group: deploy

- name: Copy Postgres configuration
  become: yes
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/9.6/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
  notify: restart postgresql

- name: Create animamagica user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: animamagica
    password: animamagica
    encrypted: yes

- name: Create animamagica database in Postgres
  become: yes
  become_user: postgres
  postgresql_db:
    name: animamagica
    owner: animamagica
    encoding: UTF-8

- name: Create bln user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: bln
    password: bln
    encrypted: yes

- name: Create bln database in Postgres
  become: yes
  become_user: postgres
  postgresql_db:
    name: bln
    owner: bln
    encoding: UTF-8
