---
- name: Install opendkim package
  become: yes
  apt: name=opendkim state=present

- name: Install postfix package
  become: yes
  apt: name=postfix state=present

- name: Install procmail package
  become: yes
  apt: name=procmail state=present

- name: Copy aliases file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/aliases'
    dest: /etc/aliases
  notify: rebuild postfix aliases

- name: Copy hostname file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/hostname'
    dest: /etc/hostname

- name: Copy hosts file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/hosts'
    dest: /etc/hosts

- name: Copy mailname file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/mailname'
    dest: /etc/mailname

- name: Copy sasldb2 file
  become: yes
  copy: src=sasldb2 dest=/etc/sasldb2

- name: Copy postfix main configuration
  become: yes
  copy: src=main.cf dest=/etc/postfix/main.cf
  notify: restart postfix

- name: Copy postfix master configuration
  become: yes
  copy: src=master.cf dest=/etc/postfix/master.cf
  notify: restart postfix

- name: Copy postfix rewrite file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/postfix/rewrite'
    dest: /etc/postfix/rewrite
  notify: restart postfix

- name: Copy postfix sasl smtpd configuration
  become: yes
  copy: src=sasl-smtpd.conf dest=/etc/postfix/sasl/smtpd.conf
  notify: restart postfix

- name: Copy postfix sasl_passwd file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/postfix/sasl_passwd'
    dest: /etc/postfix/sasl_passwd
    mode: 0600
  notify: rebuild postfix sasl_passwd

- name: Copy postfix transport file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/postfix/transport'
    dest: /etc/postfix/transport
  notify: rebuild postfix transport

- name: Copy postfix virtual file
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/postfix/virtual'
    dest: /etc/postfix/virtual
  notify: rebuild postfix virtual
