---
- name: Install email packages
  become: yes
  apt:
    state: present
    name:
      - opendkim
      - postfix
      - procmail
      - sasl2-bin

- name: Copy aliases file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/aliases'
    dest: /etc/aliases
  notify: rebuild postfix aliases

- name: Copy hostname file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/hostname'
    dest: /etc/hostname

- name: Copy hosts file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/hosts'
    dest: /etc/hosts

- name: Copy mailname file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/mailname'
    dest: /etc/mailname

- name: Copy motd file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/motd'
    dest: /etc/motd

- name: Create postfix user
  become: yes
  user:
    name: postfix
    comment: Postfix
    shell: /bin/false
    groups: opendkim,sasl

- name: Create /etc/opendkim
  become: yes
  file:
    path: /etc/opendkim
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create /etc/opendkim/keys
  become: yes
  file:
    path: /etc/opendkim/keys
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create /etc/systemd/system/opendkim.service.d
  become: yes
  file:
    path: /etc/systemd/system/opendkim.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create /var/spool/postfix/var/lib/postfix
  become: yes
  file:
    path: /var/spool/postfix/var/lib/postfix
    state: directory
    mode: 0755
    owner: postfix
    group: postfix

- name: Create /var/spool/postfix/var/run/opendkim
  become: yes
  file:
    path: /var/spool/postfix/var/run/opendkim
    state: directory
    mode: 0750
    owner: opendkim
    group: opendkim

- name: Copy opendkim configuration
  become: yes
  copy: src=opendkim.conf dest=/etc/opendkim.conf
  notify: restart opendkim

- name: Copy opendkim systemd override
  become: yes
  copy:
    src: opendkim-local.conf
    dest: /etc/systemd/system/opendkim.service.d/local.conf
  notify: restart opendkim

- name: Copy opendkim key table
  become: yes
  copy: src=opendkim/KeyTable dest=/etc/opendkim/KeyTable
  notify: restart opendkim

- name: Copy opendkim signing table
  become: yes
  copy: src=opendkim/SigningTable dest=/etc/opendkim/SigningTable
  notify: restart opendkim

- name: Copy opendkim trusted hosts
  become: yes
  copy: src=opendkim/TrustedHosts dest=/etc/opendkim/TrustedHosts
  notify: restart opendkim

- name: Copy opendkim public key
  become: yes
  copy: src=opendkim/keys/mail.txt dest=/etc/opendkim/keys/mail.txt

- name: Copy postfix main configuration
  become: yes
  copy:
    src: '{{ inventory_hostname }}/postfix/main.cf'
    dest: /etc/postfix/main.cf
  notify: restart postfix

- name: Copy postfix master configuration
  become: yes
  copy:
    src: '{{ inventory_hostname }}/postfix/master.cf'
    dest: /etc/postfix/master.cf
  notify: restart postfix

- name: Copy postfix rewrite file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/postfix/rewrite'
    dest: /etc/postfix/rewrite
  notify: restart postfix

- name: Copy postfix sasl smtpd configuration
  become: yes
  copy: src=sasl-smtpd.conf dest=/etc/postfix/sasl/smtpd.conf
  notify: restart postfix

- name: Copy postfix transport file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/postfix/transport'
    dest: /etc/postfix/transport
  notify: rebuild postfix transport

- name: Copy postfix virtual file
  become: yes
  copy:
    src: '{{ inventory_hostname }}/postfix/virtual'
    dest: /etc/postfix/virtual
  notify: rebuild postfix virtual
