---
- name: Install desktop packages
  become: yes
  apt:
    state: present
    name:
      - blender
      - ffmpeg
      - ffplay
      - fontforge
      - gimp
      - handbrake-gtk
      - inkscape
      - irssi
      - keepassxc
      - libreoffice
      - minicom
      - nethack-console
      - nextcloud-desktop
      - obs-studio
      - rdesktop
      - sakura
      - scribus
      - smbclient
      - task-cinnamon-desktop
      - tigervnc-viewer
      - transmission
      - vlc
      - wireshark

- name: Copy the grub default file
  become: yes
  copy: src=grub dest=/etc/default/grub
  notify: update grub

- name: Copy the kernel-img.conf file
  become: yes
  copy: src=kernel-img.conf dest=/etc/kernel-img.conf
  notify: update grub

- name: Install snapd
  become: yes
  apt:
    state: present
    name: snapd
  when: ansible_architecture == 'x86_64'

- name: Install desktop snaps
  become: yes
  snap:
    state: present
    name:
      - discord
      - spotify
  when: ansible_architecture == 'x86_64'
