---
- name: Install desktop brews
  homebrew:
    state: present
    name:
      - flac
      - irssi
      - minicom
      - mp4v2
      - nethack

- name: Install ffmpeg brew
  homebrew:
    name: homebrew-ffmpeg/ffmpeg/ffmpeg
    install_options: with-fdk-aac
    state: present

- name: Install desktop casks
  homebrew_cask:
    state: present
    name:
      - android-file-transfer
      - apache-directory-studio
      - discord
      - firefox
      - fontforge
      - gimp
      - handbrake
      - inkscape
      - libreoffice
      - macpass
      - mumble
      - nextcloud
      - obs
      - scribus
      - spotify
      - surge-synthesizer
      - thunderbird
      - transmission
      - vcv-rack
      - virtualbox
      - vlc

- name: Check for barrier
  stat: path=/Applications/Barrier.app
  register: barrier_result

- name: Install barrier cask
  homebrew_cask:
    state: present
    name: barrier
  when: not barrier_result.stat.exists
