---
- name: Copy the SSH public key
  copy: src=authorized_keys dest="{{ ansible_env.HOME }}/.ssh/authorized_keys"

- name: Copy the SSH configuration file
  copy: src=ssh_config dest="{{ ansible_env.HOME }}/.ssh/config"

- name: Copy the Emacs configuration file
  copy: src=emacs dest="{{ ansible_env.HOME }}/.emacs"

- name: Update and upgrade Debian packages
  become: yes
  apt: update_cache=yes upgrade=dist
  when: ansible_pkg_mgr == "apt"

- name: Update and upgrade Homebrew packages
  homebrew: update_homebrew=yes upgrade_all=yes
  when: ansible_pkg_mgr == "homebrew"
