---
- name: Copy the SSH public key
  copy: src=authorized_keys dest='{{ ansible_env.HOME }}/.ssh/authorized_keys'

- name: Copy the SSH configuration file
  copy: src=ssh_config dest='{{ ansible_env.HOME }}/.ssh/config'

- name: Copy the Emacs configuration file
  copy: src=emacs dest='{{ ansible_env.HOME }}/.emacs'

- name: Install docker-ce package on Debian
  become: yes
  apt: name=docker-ce state=present
  when:
    - ansible_machine == 'x86_64'
    - ansible_pkg_mgr == 'apt'

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: '{{ ansible_env.HOME }}/.rbenv'
    version: master

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: '{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build'
    version: master

- name: Install Ruby 2.4.1
  shell: '{{ ansible_env.HOME }}/.rbenv/bin/rbenv install -s 2.4.1'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.4.1'

- name: Install Bundler for Ruby 2.4.1
  shell: 'RBENV_VERSION=2.4.1 {{ ansible_env.HOME }}/.rbenv/shims/gem install bundler'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.4.1/bin/bundler'

- name: Install Rubocop for Ruby 2.4.1
  shell: 'RBENV_VERSION=2.4.1 {{ ansible_env.HOME }}/.rbenv/shims/gem install rubocop-rspec'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.4.1/bin/rubocop'

- name: Set default Ruby
  shell: '{{ ansible_env.HOME }}/.rbenv/bin/rbenv global system'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/version'
