---
- name: Copy the SSH public key
  copy: src=authorized_keys dest='{{ ansible_env.HOME }}/.ssh/authorized_keys'

- name: Copy the SSH configuration file
  copy: src=ssh_config dest='{{ ansible_env.HOME }}/.ssh/config'

- name: Copy the Emacs configuration file
  copy: src=emacs dest='{{ ansible_env.HOME }}/.emacs'

- name: Copy the git configuration file
  copy: src=gitconfig dest='{{ ansible_env.HOME }}/.gitconfig'

- name: Copy the screen configuration file
  copy: src=screenrc dest='{{ ansible_env.HOME }}/.screenrc'

- include: x11.yml
  when: ansible_pkg_mgr == 'apt'

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: '{{ ansible_env.HOME }}/.rbenv'
    version: master

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: '{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build'
    version: master

- name: Install Ruby 2.6.5
  shell: '{{ ansible_env.HOME }}/.rbenv/bin/rbenv install -s 2.6.5'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.6.5'

- name: Install Bundler for Ruby 2.6.5
  shell: '{{ ansible_env.HOME }}/.rbenv/shims/gem install bundler:2.0.2'
  environment:
    RBENV_VERSION: 2.6.5
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2'

- name: Install haml for Ruby 2.6.5
  shell: '{{ ansible_env.HOME }}/.rbenv/shims/gem install haml'
  environment:
    RBENV_VERSION: 2.6.5
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.6.5/bin/haml'

- name: Install rubocop-performance for Ruby 2.6.5
  shell: '{{ ansible_env.HOME }}/.rbenv/shims/gem install rubocop-performance:1.5.0'
  environment:
    RBENV_VERSION: 2.6.5
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-performance-1.5.0'

- name: Install rubocop-rspec for Ruby 2.6.5
  shell: '{{ ansible_env.HOME }}/.rbenv/shims/gem install rubocop-rspec:1.36.0'
  environment:
    RBENV_VERSION: 2.6.5
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.36.0'

- name: Install Sass for Ruby 2.6.5
  shell: '{{ ansible_env.HOME }}/.rbenv/shims/gem install sass'
  environment:
    RBENV_VERSION: 2.6.5
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.6.5/bin/scss'

- name: Set default Ruby
  shell: '{{ ansible_env.HOME }}/.rbenv/bin/rbenv global system'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/version'

- name: Install linode-cli package when using Homebrew
  pip: name=linode-cli
  when: ansible_pkg_mgr == 'homebrew'
