---
- include: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_pkg_mgr }}.yml'
      skip: true

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: '{{ ansible_env.HOME }}/.rbenv'
    version: master

- name: Install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: '{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build'
    version: master

- name: Install Ruby 2.7.0
  command: '{{ ansible_env.HOME }}/.rbenv/bin/rbenv install -s 2.7.0'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.7.0'

- name: Install Bundler for Ruby 2.7.0
  command: '{{ ansible_env.HOME }}/.rbenv/shims/gem install bundler:2.1.2'
  environment:
    RBENV_VERSION: 2.7.0
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.2'

- name: Create rbenv gems directory
  file:
    path: '{{ ansible_env.HOME }}/.rbenv/gems'
    state: directory

- name: Copy standard Gemfile
  copy:
    src: Gemfile
    dest: '{{ ansible_env.HOME }}/.rbenv/gems/Gemfile'

- name: Copy standard Gemfile.lock
  copy:
    src: Gemfile.lock
    dest: '{{ ansible_env.HOME }}/.rbenv/gems/Gemfile.lock'

- name: Install standard gems for Ruby 2.7.0
  command: '{{ ansible_env.HOME }}/.rbenv/shims/bundle install --gemfile {{ ansible_env.HOME }}/.rbenv/gems/Gemfile'
  environment:
    RBENV_VERSION: 2.7.0
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/versions/2.7.0/bin/scss'

- name: Set default Ruby
  command: '{{ ansible_env.HOME }}/.rbenv/bin/rbenv global system'
  args:
    creates: '{{ ansible_env.HOME }}/.rbenv/version'

- name: Install linode-cli package when using Homebrew
  pip: name=linode-cli executable=pip3
  when: ansible_pkg_mgr == 'homebrew'
