---
- name: Install intranet packages
  become: yes
  apt:
    state: present
    name:
      - apacheds
      - cups
      - dnsmasq
      - dovecot-imapd
      - dovecot-ldap
      - dovecot-lmtpd
      - dovecot-managesieved
      - dovecot-sieve
      - firmware-linux-nonfree
      - iftop
      - ipv6calc
      - jenkins
      - ldap-utils
      - miniupnpd
      - motion
      - olsrd
      - openvpn
      - php
      - php-apcu
      - php-bcmath
      - php-curl
      - php-fpm
      - php-gd
      - php-intl
      - php-imagick
      - php-ldap
      - php-mbstring
      - php-pgsql
      - php-redis
      - php-xml
      - php-zip
      - postgresql
      - reprepro
      - rsnapshot
      - samba
      - spamassassin
      - spamc
      - tftpd-hpa
      - tigervnc-standalone-server
      - zabbix-frontend-php
      - zabbix-server-pgsql

- name: Install wondercake
  become: yes
  copy: src=wondercake dest=/usr/local/sbin/wondercake mode=0755

- name: Copy cups configuration
  become: yes
  copy: src=cupsd.conf dest=/etc/cups/cupsd.conf backup=yes

- name: Copy rsnapshot configuration
  become: yes
  copy: src=rsnapshot.conf dest=/etc/rsnapshot.conf backup=yes

- name: Copy rsnapshot crontab
  become: yes
  copy: src=rsnapshot.cron dest=/etc/cron.d/rsnapshot backup=yes

- name: Copy network interfaces
  become: yes
  copy: src=interfaces dest=/etc/network/interfaces backup=yes

- name: Copy DHCP client configuration
  become: yes
  copy: src=dhclient.conf dest=/etc/dhcp backup=yes

- name: Copy iptables rules
  become: yes
  copy: src=iptables.rules dest=/etc/network/iptables.rules backup=yes

- name: Copy prefix_delegation script
  become: yes
  copy: src=prefix_delegation dest=/etc/dhcp/dhclient-exit-hooks.d/ backup=yes

- name: Copy smb.conf
  become: yes
  copy: src=smb.conf dest=/etc/samba/smb.conf backup=yes
  notify: restart smbd

- name: Copy sysctl.conf
  become: yes
  copy: src=sysctl.conf dest=/etc/sysctl.conf backup=yes
  notify: reload sysctl

- name: Copy vncserver-keegan service
  become: yes
  copy: src=vncserver-keegan.service dest=/etc/systemd/system/ backup=yes

- name: Copy dnsmasq configuration
  become: yes
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf backup=yes
  notify: restart dnsmasq

- name: Copy miniupnpd configuration
  become: yes
  copy: src=miniupnpd.conf dest=/etc/miniupnpd/miniupnpd.conf backup=yes

- name: Copy php-fpm configuration
  become: yes
  copy: src=php.ini dest=/etc/php/7.3/fpm/php.ini backup=yes
  notify: restart php-fpm

- name: Copy php-fpm pool configuration
  become: yes
  copy: src=www.conf dest=/etc/php/7.3/fpm/pool.d/www.conf backup=yes
  notify: restart php-fpm

- name: Schedule nextcloud cron
  become: yes
  become_user: www-data
  cron:
    name: nextcloud
    job: /usr/bin/php -f /var/www/nextcloud/cron.php
    user: www-data

- name: Copy the bashrc for the jenkins user
  become: yes
  copy:
    src: roles/machine/files/bashrc
    dest: /var/lib/jenkins/.bashrc
    owner: jenkins
    group: jenkins

- name: Copy the profile for the jenkins user
  become: yes
  copy:
    src: roles/machine/files/profile
    dest: /var/lib/jenkins/.profile
    owner: jenkins
    group: jenkins

- name: Install rbenv for the jenkins user
  become: yes
  become_user: jenkins
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /var/lib/jenkins/.rbenv
    version: master

- name: Install ruby-build for the jenkins user
  become: yes
  become_user: jenkins
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /var/lib/jenkins/.rbenv/plugins/ruby-build
    version: master

- name: Install Ruby 2.7.1 for the jenkins user
  become: yes
  become_user: jenkins
  command: /var/lib/jenkins/.rbenv/bin/rbenv install -s 2.7.1
  args:
    creates: /var/lib/jenkins/.rbenv/versions/2.7.1

- name: Install Bundler for the jenkins user
  become: yes
  become_user: jenkins
  command: /var/lib/jenkins/.rbenv/shims/gem install bundler:2.1.4
  environment:
    RBENV_VERSION: 2.7.1
  args:
    creates: /var/lib/jenkins/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4

- name: Install pip packages for the jenkins user
  become: yes
  become_user: jenkins
  pip:
    executable: pip3
    name:
      - ansible
      - ansible-lint
