---
- name: Install cups package
  become: yes
  apt: name=cups state=present

- name: Copy cups configuration
  become: yes
  copy: src=cupsd.conf dest=/etc/cups/cupsd.conf

- name: Install dnsmasq package
  become: yes
  apt: name=dnsmasq state=present

- name: Install ipv6calc package
  become: yes
  apt: name=ipv6calc state=present

- name: Install zabbix-server-pgsql package
  become: yes
  apt: name=zabbix-server-pgsql state=present

- name: Install rsnapshot package
  become: yes
  apt: name=rsnapshot state=present

- name: Copy rsnapshot configuration
  become: yes
  copy: src=rsnapshot.conf dest=/etc/rsnapshot.conf

- name: Copy rsnapshot crontab
  become: yes
  copy: src=rsnapshot.cron dest=/etc/cron.d/rsnapshot

- name: Install squid package
  become: yes
  apt: name=squid state=present

- name: Install jenkins package
  become: yes
  apt: name=jenkins state=present

- name: Install docker-ce package
  become: yes
  apt: name=docker-ce state=present

- name: Copy docker daemon configuration
  become: yes
  copy: src=docker-daemon.json dest=/etc/docker/daemon.json
  notify: restart docker

- name: Copy network interfaces
  become: yes
  copy: src=interfaces dest=/etc/network/interfaces

- name: Copy iptables rules
  become: yes
  copy: src=iptables.rules dest=/etc/network/iptables.rules

- name: Copy prefix_delegation script
  become: yes
  copy: src=prefix_delegation dest=/etc/dhcp/dhclient-exit-hooks.d/

- name: Copy sysctl.conf
  become: yes
  copy: src=sysctl.conf dest=/etc/sysctl.conf
  notify: reload sysctl

- name: Copy dnsmasq configuration
  become: yes
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  notify: restart dnsmasq
