---
- name: Install zabbix-server-pgsql package
  become: yes
  apt: name=zabbix-server-pgsql state=present

- name: Install rsnapshot package
  become: yes
  apt: name=rsnapshot state=present

- name: Copy rsnapshot configuration
  become: yes
  copy: src=rsnapshot.conf dest=/etc/rsnapshot.conf

- name: Copy rsnapshot crontab
  become: yes
  copy: src=rsnapshot.cron dest=/etc/cron.d/rsnapshot

- name: Install squid package
  become: yes
  apt: name=squid state=present

- name: Install jenkins package
  become: yes
  apt: name=jenkins state=present

- name: Install docker-ce package
  become: yes
  apt: name=docker-ce state=present

- name: Copy docker daemon configuration
  become: yes
  copy: src=docker-daemon.json dest=/etc/docker/daemon.json
  notify: restart docker
