---
- name: Install intranet packages
  become: yes
  apt:
    state: present
    name:
      - cups
      - docker-ce
      - dnsmasq
      - firmware-linux-nonfree
      - iftop
      - ipv6calc
      - jenkins
      - olsrd
      - openvpn
      - owncloud-files
      - php-apcu
      - php-curl
      - php-fpm
      - php-gd
      - php-intl
      - php-mbstring
      - php-pgsql
      - php-redis
      - php-xml
      - php-zip
      - postgresql
      - rsnapshot
      - samba
      - shairport-sync
      - zabbix-server-pgsql

- name: Copy cups configuration
  become: yes
  copy: src=cupsd.conf dest=/etc/cups/cupsd.conf

- name: Copy rsnapshot configuration
  become: yes
  copy: src=rsnapshot.conf dest=/etc/rsnapshot.conf

- name: Copy rsnapshot crontab
  become: yes
  copy: src=rsnapshot.cron dest=/etc/cron.d/rsnapshot

- name: Copy docker daemon configuration
  become: yes
  copy: src=docker-daemon.json dest=/etc/docker/daemon.json
  notify: restart docker

- name: Copy network interfaces
  become: yes
  copy: src=interfaces dest=/etc/network/interfaces

- name: Copy iptables rules
  become: yes
  copy: src=iptables.rules dest=/etc/network/iptables.rules

- name: Copy prefix_delegation script
  become: yes
  copy: src=prefix_delegation dest=/etc/dhcp/dhclient-exit-hooks.d/

- name: Copy smb.conf
  become: yes
  copy: src=smb.conf dest=/etc/samba/smb.conf
  notify: restart smbd

- name: Copy shairport-sync.conf
  become: yes
  copy: src=shairport-sync.conf dest=/etc/shairport-sync.conf
  notify: restart shairport-sync

- name: Copy sysctl.conf
  become: yes
  copy: src=sysctl.conf dest=/etc/sysctl.conf
  notify: reload sysctl

- name: Copy dnsmasq configuration
  become: yes
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Copy php fpm pool configuration
  become: yes
  copy: src=www.conf dest=/etc/php/7.0/fpm/pool.d/www.conf
  notify: restart php-fpm

- name: Copy owncloud configuration
  become: yes
  copy:
    src: owncloud-config.php
    dest: /var/www/owncloud/config/config.php
    owner: www-data
    group: www-data
    mode: 0640

- name: Create owncloud user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: owncloud
    password: owncloud
    encrypted: yes

- name: Create owncloud database in Postgres
  become: yes
  become_user: postgres
  postgresql_db:
    name: owncloud
    owner: owncloud
    encoding: UTF-8

- name: Schedule owncloud cron
  become: yes
  become_user: www-data
  cron:
    name: owncloud
    job: /usr/bin/php -f /var/www/owncloud/cron.php
    user: www-data
