---
- name: Install intranet packages
  become: yes
  apt:
    state: present
    name:
      - apacheds
      - cups
      - dnsmasq
      - dovecot-imapd
      - dovecot-ldap
      - dovecot-lmtpd
      - firmware-linux-nonfree
      - icecast2
      - iftop
      - ipv6calc
      - jenkins
      - ldap-utils
      - motion
      - mumble-server
      - olsrd
      - openvpn
      - php
      - php-apcu
      - php-bcmath
      - php-curl
      - php-fpm
      - php-gd
      - php-intl
      - php-imagick
      - php-ldap
      - php-mbstring
      - php-pgsql
      - php-redis
      - php-xml
      - php-zip
      - postgresql
      - rsnapshot
      - samba
      - tigervnc-standalone-server
      - zabbix-frontend-php
      - zabbix-server-pgsql

- name: Copy cups configuration
  become: yes
  copy: src=cupsd.conf dest=/etc/cups/cupsd.conf

- name: Copy rsnapshot configuration
  become: yes
  copy: src=rsnapshot.conf dest=/etc/rsnapshot.conf

- name: Copy rsnapshot crontab
  become: yes
  copy: src=rsnapshot.cron dest=/etc/cron.d/rsnapshot

- name: Copy network interfaces
  become: yes
  copy: src=interfaces dest=/etc/network/interfaces

- name: Copy DHCP client configuration
  become: yes
  copy: src=dhclient.conf dest=/etc/dhcp

- name: Copy iptables rules
  become: yes
  copy: src=iptables.rules dest=/etc/network/iptables.rules

- name: Copy prefix_delegation script
  become: yes
  copy: src=prefix_delegation dest=/etc/dhcp/dhclient-exit-hooks.d/

- name: Copy smb.conf
  become: yes
  copy: src=smb.conf dest=/etc/samba/smb.conf
  notify: restart smbd

- name: Copy sysctl.conf
  become: yes
  copy: src=sysctl.conf dest=/etc/sysctl.conf
  notify: reload sysctl

- name: Copy vncserver-keegan service
  become: yes
  copy: src=vncserver-keegan.service dest=/etc/systemd/system/
  notify: restart vncserver-keegan

- name: Copy dnsmasq configuration
  become: yes
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Copy php-fpm configuration
  become: yes
  copy: src=php.ini dest=/etc/php/7.3/fpm/php.ini
  notify: restart php-fpm

- name: Copy php-fpm pool configuration
  become: yes
  copy: src=www.conf dest=/etc/php/7.3/fpm/pool.d/www.conf
  notify: restart php-fpm

- name: Create nextcloud user in Postgres
  become: yes
  become_user: postgres
  postgresql_user:
    name: nextcloud
    password: nextcloud
    encrypted: yes

- name: Create nextcloud database in Postgres
  become: yes
  become_user: postgres
  postgresql_db:
    name: nextcloud
    owner: nextcloud
    encoding: UTF-8

- name: Schedule nextcloud cron
  become: yes
  become_user: www-data
  cron:
    name: nextcloud
    job: /usr/bin/php -f /var/www/nextcloud/cron.php
    user: www-data

- name: Install rbenv for the jenkins user
  become: yes
  become_user: jenkins
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /var/lib/jenkins/.rbenv
    version: master

- name: Install ruby-build for the jenkins user
  become: yes
  become_user: jenkins
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /var/lib/jenkins/.rbenv/plugins/ruby-build
    version: master

- name: Copy the bashrc for the jenkins user
  become: yes
  copy:
    src: roles/machine/files/bashrc
    dest: /var/lib/jenkins/.bashrc
    owner: jenkins
    group: jenkins

- name: Copy the profile for the jenkins user
  become: yes
  copy:
    src: roles/machine/files/profile
    dest: /var/lib/jenkins/.profile
    owner: jenkins
    group: jenkins

- name: Install Ruby 2.6.5 for the jenkins user
  become: yes
  become_user: jenkins
  command: /var/lib/jenkins/.rbenv/bin/rbenv install -s 2.6.5
  args:
    creates: /var/lib/jenkins/.rbenv/versions/2.6.5

- name: Install Bundler for the jenkins user
  become: yes
  become_user: jenkins
  command: /var/lib/jenkins/.rbenv/shims/gem install bundler:2.0.2
  environment:
    RBENV_VERSION: 2.6.5
  args:
    creates: /var/lib/jenkins/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.0.2
