---
- name: Install zabbix-server-pgsql package
  become: yes
  apt: name=zabbix-server-pgsql state=present

- name: Install jenkins package
  become: yes
  apt: name=jenkins state=present

- name: Install docker-ce package
  become: yes
  apt: name=docker-ce state=present

- name: Copy docker daemon configuration
  become: yes
  copy: src=docker-daemon.json dest=/etc/docker/daemon.json
  notify: restart docker
