; -*- zone -*-

; quinn.tk. Keegan's.

$TTL 2d

@ IN    SOA     len hostmaster (
        ; serial
        2019021800
        ; refresh
        30M
        ; retry
        15M
        ; expiry
        4W
        ; minimum
        1h
        )

        NS      ns1.linode.com.
        NS      ns2.linode.com.
        NS      ns3.linode.com.
        NS      ns4.linode.com.
        NS      ns5.linode.com.

        MX      10      len

        A       45.79.65.28
        AAAA    2600:3c01::f03c:91ff:fee9:47cb

        TXT     "google-site-verification=1OfHR563epbyfz3VTSwSMZYbwATJ6j3vsAXSND-0yIQ"
        TXT     "v=DMARC1;p=quarantine;pct=100;rua=mailto:postmaster@quinn.tk"
        TXT     "v=spf1 mx a include:_spf.google.com ~all"
mail._domainkey TXT "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/99IBr17xO4t61WBOl46n5W0WN3zeRg6HDIMKzXDtFZ0051OI2kqWmIFJOuTRXE82yJVtZnQVVoealfGBf1Ly2YuAfxOKdgIb93UGVzcB2oVhOJl3JYQBAKSQS4eFeI18MN/LT8NpEGK16T9qOWJKdG18YeodoGaiXLK3iWkUrwIDAQAB"

www     CNAME   @

len     A       45.79.65.28
len     AAAA    2600:3c01::f03c:91ff:fee9:47cb
len     TXT     "v=spf1 a -all"

pi      A       89.18.165.159
pi      AAAA    2a00:f10:103:201:ba27:ebff:fe73:17b5
pi      TXT     "v=spf1 a -all"

scrap   A       67.189.70.230
scrap   AAAA    2601:1c2:4c00:e66d::1
scrap   MX      10      len
scrap   TXT     "v=spf1 mx a -all"

animamagica-staging     CNAME   scrap
basslines-staging       CNAME   scrap
cloud                   CNAME   scrap
cwnmyr                  CNAME   len
cwnmyr-staging          CNAME   scrap
jenkins                 CNAME   scrap
lists                   CNAME   len
redmine                 CNAME   len
staging                 CNAME   scrap
zabbix                  CNAME   scrap
