---
- name: Add jenkins APT key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  when: ansible_architecture == 'x86_64'

- name: Add multimedia APT key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 5C808C2B65558117

- name: Add nodesource APT key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: ansible_architecture == 'x86_64'

- name: Add yarn APT key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  when: ansible_architecture == 'x86_64'

- name: Copy APT sources
  become: yes
  copy: src='sources.list.{{ ansible_architecture }}' dest=/etc/apt/sources.list

- name: Upgrade packages
  become: yes
  apt: update_cache=yes upgrade=dist

- name: Install machine packages
  become: yes
  apt:
    state: present
    name:
      - apt-listchanges
      - bind9utils
      - curl
      - deborphan
      - dos2unix
      - emacs
      - file
      - finger
      - git
      - lftp
      - mlocate
      - nmap
      - nextcloud-desktop-cmd
      - p7zip
      - rsync
      - screen
      - sox
      - tcpdump
      - unrar
      - unzip
