---
- name: Add jenkins APT key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  when: ansible_architecture == 'x86_64'

- name: Add multimedia APT key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 5C808C2B65558117

- name: Add nodesource APT key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: ansible_architecture == 'x86_64'

- name: Add yarn APT key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  when: ansible_architecture == 'x86_64'

- name: Copy APT default release configuration
  become: yes
  copy: src=99defaultrelease dest=/etc/apt/apt.conf.d/

- name: Copy APT sources
  become: yes
  copy: src='sources.list.{{ ansible_architecture }}' dest=/etc/apt/sources.list

- name: Upgrade packages
  become: yes
  apt: update_cache=yes upgrade=dist

- name: Install machine packages
  become: yes
  apt:
    state: present
    name:
      - aide
      - apt-listchanges
      - bind9utils
      - curl
      - deborphan
      - dos2unix
      - emacs
      - figlet
      - file
      - finger
      - fonts-hack
      - git
      - lftp
      - mlocate
      - nmap
      - p7zip
      - rsync
      - screen
      - sox
      - tcpdump
      - unrar
      - unzip

- name: Install nextcloud-desktop-cmd from backports
  become: yes
  apt:
    state: present
    name: nextcloud-desktop-cmd
    default_release: buster-backports

- name: Copy 80_aide_local config fragment
  become: yes
  copy: src=80_aide_local dest=/etc/aide/aide.conf.d/80_aide_local
