---
- name: Add Debian APT key for jessie
  become: yes
  apt_key:
    url: 'https://ftp-master.debian.org/keys/archive-key-8.asc'
    state: present

- name: Add Debian APT key for jessie/updates
  become: yes
  apt_key:
    url: 'https://ftp-master.debian.org/keys/archive-key-8-security.asc'
    state: present

- name: Add Debian APT key for stretch
  become: yes
  apt_key:
    url: 'https://ftp-master.debian.org/keys/archive-key-9.asc'
    state: present

- name: Add Debian APT key for stretch/updates
  become: yes
  apt_key:
    url: 'https://ftp-master.debian.org/keys/archive-key-9-security.asc'
    state: present

- name: Add Raspbian APT key
  become: yes
  apt_key:
    url: 'https://archive.raspbian.org/raspbian.public.key'
    state: present

- name: Copy APT sources
  become: yes
  copy: src='sources.list.{{ ansible_architecture }}' dest=/etc/apt/sources.list

- name: Add docker APT key
  become: yes
  apt_key:
    url: 'https://download.docker.com/linux/debian/gpg'
    state: present

- name: Add docker APT source
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
    filename: docker

- name: Add nodesource APT key
  become: yes
  apt_key:
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    state: present

- name: Enable nodesource APT source
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://deb.nodesource.com/node_8.x stretch main
    state: present
    filename: nodesource

- name: Add yarn APT key
  become: yes
  apt_key:
    url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    state: present

- name: Enable yarn APT source
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn

- name: Update and upgrade packages
  become: yes
  apt: update_cache=yes upgrade=dist

- name: Install deborphan package
  become: yes
  apt: name=deborphan state=present

- name: Install apt-listchanges package
  become: yes
  apt: name=apt-listchanges state=present

- name: Install emacs package on Debian
  become: yes
  apt: name=emacs25 state=present

- name: Install file package
  become: yes
  apt: name=file state=present

- name: Install git package
  become: yes
  apt: name=git state=present

- name: Install harden-servers package
  become: yes
  apt: name=harden-servers state=present

- name: Install mlocate package
  become: yes
  apt: name=mlocate state=present

- name: Install nmap package
  become: yes
  apt: name=nmap state=present

- name: Install screen package
  become: yes
  apt: name=screen state=present

- name: Install unzip package
  become: yes
  apt: name=unzip state=present
