---
- name: Add Debian APT key for stretch
  become: yes
  apt_key:
    url: 'https://ftp-master.debian.org/keys/archive-key-9.asc'
    state: present

- name: Add Debian APT key for stretch/updates
  become: yes
  apt_key:
    url: 'https://ftp-master.debian.org/keys/archive-key-9-security.asc'
    state: present

- name: Add Raspbian APT key
  become: yes
  apt_key:
    url: 'https://archive.raspbian.org/raspbian.public.key'
    state: present

- name: Copy APT sources
  become: yes
  copy: src='sources.list.{{ ansible_architecture }}' dest=/etc/apt/sources.list

- name: Add nodesource APT key
  become: yes
  apt_key:
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    state: present

- name: Enable nodesource APT source
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x stretch main
    state: present
    filename: nodesource

- name: Add owncloud APT key
  become: yes
  apt_key:
    url: https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key
    state: present

- name: Enable owncloud APT source
  become: yes
  apt_repository:
    repo: deb http://download.owncloud.org/download/repositories/production/Debian_9.0/ /
    state: present
    filename: owncloud

- name: Add yarn APT key
  become: yes
  apt_key:
    url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    state: present

- name: Enable yarn APT source
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn

- name: Update and upgrade packages
  become: yes
  apt: update_cache=yes upgrade=dist

- name: Install machine packages
  become: yes
  apt:
    state: present
    name:
      - apt-listchanges
      - curl
      - deborphan
      - emacs25
      - file
      - finger
      - git
      - lftp
      - mlocate
      - nmap
      - screen
      - tcpdump
      - unzip
