---
- name: Add jenkins APT key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  when: ansible_architecture == 'x86_64'

- name: Add multimedia APT key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 5C808C2B65558117

- name: Add nodesource APT key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: ansible_architecture == 'x86_64'

- name: Add qtk.io APT key
  become: yes
  apt_key:
    url: https://xmit.qtk.io/debian/repo.gpg.key
    state: present

- name: Add wazuh APT key
  become: yes
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present
  when: ansible_architecture == 'x86_64'

- name: Copy APT sources
  become: yes
  copy: src='sources.list.{{ ansible_architecture }}' dest=/etc/apt/sources.list

- name: Upgrade packages
  become: yes
  apt: update_cache=yes upgrade=dist

- name: Install machine packages
  become: yes
  apt:
    state: present
    name:
      - aide
      - apt-listchanges
      - bind9utils
      - curl
      - dbconfig-no-thanks
      - deborphan
      - dos2unix
      - emacs
      - figlet
      - file
      - finger
      - fonts-hack
      - git
      - lftp
      - mlocate
      - nextcloud-desktop-cmd
      - nmap
      - p7zip
      - postfix
      - python3-pip
      - rkhunter
      - rsync
      - screen
      - sox
      - tcpdump
      - unrar
      - unzip

- name: Copy aide default file
  become: yes
  copy: src=aide.default dest=/etc/default/aide

- name: Copy aide local configuration fragment
  become: yes
  copy: src=aide.local dest=/etc/aide/aide.conf.d/80_aide_local

- name: Copy rkhunter default file
  become: yes
  copy: src=rkhunter dest=/etc/default/rkhunter
