---
- name: Update and upgrade Homebrew packages
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install emacs cask
  homebrew_cask: name=emacs state=present

- name: Install p7zip brew
  homebrew: name=p7zip state=present
