---
- name: Update and upgrade Homebrew packages
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install pre-dependency casks
  homebrew_cask:
    state: present
    name:
      - java
      - xquartz

- name: Install machine brews
  homebrew:
    state: present
    name:
      - carthage
      - dos2unix
      - lftp
      - nmap
      - p7zip
      - wget

- name: Install machine casks
  homebrew_cask:
    state: present
    name:
      - emacs
      - font-3270
      - font-abeezee
      - font-abel
      - font-aboriginal-sans
      - font-aboriginal-serif
      - font-abril-fatface
      - font-accordance
      - font-acme
      - font-actor
      - font-adamina
      - font-advent-pro
      - font-african-sans
      - font-african-serif
      - font-aguafina-script
      - font-akronim
      - font-aladin
      - font-aldrich
      - font-alex-brush
      - font-alfa-slab-one
      - font-alice
      - font-alike
      - font-alike-angular
      - font-allan
      - font-allerta
      - font-allerta-stencil
      - font-allura
      - font-almendra
      - font-almendra-display
      - font-almendra-sc
      - font-amarante
      - font-amaranth
      - font-amatic-sc
      - font-amethysta
      - font-anaheim
      - font-andada
      - font-andada-sc
      - font-angkor
      - font-annie-use-your-telescope
      - font-anonymous-pro
      - font-antic
      - font-antic-didone
      - font-antic-slab
      - font-anton
      - font-arapey
      - font-arbutus
      - font-arbutus-slab
      - font-architects-daughter
      - font-archivo-black
      - font-archivo-narrow
      - font-arimo
      - font-arizonia
      - font-armata
      - font-artifika
      - font-arvo
      - font-asap
      - font-asset
      - font-astloch
      - font-asul
      - font-atomic-age
      - font-aubrey
      - font-audiowide
      - font-autour-one
      - font-average
      - font-average-mono
      - font-averia-gruesa-libre
      - font-averia-libre
      - font-averia-sans-libre
      - font-averia-serif-libre
      - font-bad-script
      - font-balthazar
      - font-bangers
      - font-basic
      - font-battambang
      - font-baumans
      - font-bayon
      - font-belgrano
      - font-belleza
      - font-benchnine
      - font-bentham
      - font-berkshire-swash
      - font-bevan
      - font-bigelow-rules
      - font-bigshot-one
      - font-bilbo
      - font-bilbo-swash-caps
      - font-bitstream-vera
      - font-black-ops-one
      - font-bokor
      - font-bonbon
      - font-boogaloo
      - font-bowlby-one
      - font-bowlby-one-sc
      - font-brawler
      - font-bree-serif
      - font-bubblegum-sans
      - font-bubbler-one
      - font-buda
      - font-buenard
      - font-butcherman
      - font-butler
      - font-butterfly-kids
      - font-cabin
      - font-cabin-condensed
      - font-cabin-sketch
      - font-caesar-dressing
      - font-cagliostro
      - font-calligraffitti
      - font-cambo
      - font-candal
      - font-cantarell
      - font-cantata-one
      - font-cantora-one
      - font-capriola
      - font-carme
      - font-carrois-gothic
      - font-carrois-gothic-sc
      - font-carter-one
      - font-caudex
      - font-cedarville-cursive
      - font-ceviche-one
      - font-changa-one
      - font-chango
      - font-chau-philomene-one
      - font-chela-one
      - font-chelsea-market
      - font-chenla
      - font-cherry-cream-soda
      - font-cherry-swash
      - font-chewy
      - font-chicle
      - font-chivo
      - font-cinzel
      - font-cinzel-decorative
      - font-clicker-script
      - font-coda
      - font-coda-caption
      - font-code
      - font-codystar
      - font-combo
      - font-comfortaa
      - font-coming-soon
      - font-concert-one
      - font-condiment
      - font-content
      - font-contrail-one
      - font-convergence
      - font-cookie
      - font-copse
      - font-corben
      - font-courgette
      - font-cousine
      - font-coustard
      - font-covered-by-your-grace
      - font-crafty-girls
      - font-creepster
      - font-crete-round
      - font-crimson-text
      - font-croissant-one
      - font-crushed
      - font-cuprum
      - font-cutive
      - font-cutive-mono
      - font-damion
      - font-dancing-script
      - font-dangrek
      - font-dawning-of-a-new-day
      - font-days-one
      - font-delius
      - font-delius-swash-caps
      - font-delius-unicase
      - font-della-respira
      - font-denk-one
      - font-devonshire
      - font-diplomata
      - font-diplomata-sc
      - font-domine
      - font-donegal-one
      - font-doppio-one
      - font-dorsa
      - font-dosis
      - font-dr-sugiyama
      - font-duru-sans
      - font-dynalight
      - font-eagle-lake
      - font-eater
      - font-economica
      - font-electrolize
      - font-elsie
      - font-elsie-swash-caps
      - font-emblema-one
      - font-emilys-candy
      - font-engagement
      - font-englebert
      - font-enriqueta
      - font-erica-one
      - font-esteban
      - font-euphoria-script
      - font-ewert
      - font-exo
      - font-exo2
      - font-expletus-sans
      - font-fanwood-text
      - font-fascinate
      - font-fascinate-inline
      - font-faster-one
      - font-fasthand
      - font-fauna-one
      - font-federant
      - font-federo
      - font-felipa
      - font-fenix
      - font-finger-paint
      - font-fjalla-one
      - font-fjord-one
      - font-flamenco
      - font-flavors
      - font-fondamento
      - font-fontdiner-swanky
      - font-forum
      - font-francois-one
      - font-freckle-face
      - font-fredericka-the-great
      - font-fredoka-one
      - font-freehand
      - font-fresca
      - font-frijole
      - font-fruktur
      - font-fugaz-one
      - font-gabriela
      - font-gafata
      - font-galdeano
      - font-galindo
      - font-geo
      - font-geostar
      - font-geostar-fill
      - font-germania-one
      - font-gfs-didot
      - font-gfs-neohellenic
      - font-gilda-display
      - font-give-you-glory
      - font-glass-antiqua
      - font-glegoo
      - font-gloria-hallelujah
      - font-goblin-one
      - font-gochi-hand
      - font-gorditas
      - font-goudy-bookletter1911
      - font-graduate
      - font-grand-hotel
      - font-gravitas-one
      - font-great-vibes
      - font-griffy
      - font-gruppo
      - font-gudea
      - font-habibi
      - font-hack
      - font-hammersmith-one
      - font-hanalei
      - font-hanalei-fill
      - font-handlee
      - font-hanuman
      - font-happy-monkey
      - font-headland-one
      - font-henny-penny
      - font-herr-von-muellerhoff
      - font-holtwood-one-sc
      - font-homenaje
      - font-iceberg
      - font-iceland
      - font-im-fell-double-pica
      - font-im-fell-double-pica-sc
      - font-im-fell-dw-pica
      - font-im-fell-dw-pica-sc
      - font-im-fell-english
      - font-im-fell-english-sc
      - font-im-fell-french-canon
      - font-im-fell-french-canon-sc
      - font-im-fell-great-primer
      - font-im-fell-great-primer-sc
      - font-imprima
      - font-inconsolata
      - font-inder
      - font-indie-flower
      - font-inika
      - font-istok-web
      - font-italiana
      - font-italianno
      - font-jacques-francois
      - font-jacques-francois-shadow
      - font-jim-nightshade
      - font-jockey-one
      - font-jolly-lodger
      - font-josefin-sans
      - font-josefin-slab
      - font-joti-one
      - font-judson
      - font-julee
      - font-julius-sans-one
      - font-junge
      - font-jura
      - font-just-me-again-down-here
      - font-kameron
      - font-kantumruy
      - font-karla
      - font-kaushan-script
      - font-kavoon
      - font-kdam-thmor
      - font-keania-one
      - font-kelly-slab
      - font-kenia
      - font-khmer
      - font-kite-one
      - font-knewave
      - font-kotta-one
      - font-koulen
      - font-kreon
      - font-krona-one
      - font-la-belle-aurore
      - font-lancelot
      - font-lateef
      - font-league-script
      - font-leckerli-one
      - font-ledger
      - font-lekton
      - font-lemon
      - font-libre-baskerville
      - font-life-savers
      - font-lilita-one
      - font-lily-script-one
      - font-limelight
      - font-linden-hill
      - font-lobster
      - font-lobster-two
      - font-londrina-outline
      - font-londrina-shadow
      - font-londrina-sketch
      - font-londrina-solid
      - font-lora
      - font-love-ya-like-a-sister
      - font-loved-by-the-king
      - font-lovers-quarrel
      - font-luckiest-guy
      - font-lusitana
      - font-lustria
      - font-macondo
      - font-macondo-swash-caps
      - font-magra
      - font-mako
      - font-marcellus
      - font-marcellus-sc
      - font-marck-script
      - font-margarine
      - font-marko-one
      - font-marmelad
      - font-marvel
      - font-mate
      - font-mate-sc
      - font-maven-pro
      - font-mclaren
      - font-meddon
      - font-medievalsharp
      - font-medula-one
      - font-megrim
      - font-meie-script
      - font-merienda
      - font-merienda-one
      - font-merriweather
      - font-merriweather-sans
      - font-metal
      - font-metal-mania
      - font-metamorphous
      - font-metrophobic
      - font-michroma
      - font-milonga
      - font-miltonian
      - font-miltonian-tattoo
      - font-miniver
      - font-miss-fajardose
      - font-modern-antiqua
      - font-molengo
      - font-molle
      - font-monda
      - font-monofett
      - font-monoton
      - font-monsieur-la-doulaise
      - font-montaga
      - font-montez
      - font-montserrat-subrayada
      - font-moul
      - font-moulpali
      - font-mountains-of-christmas
      - font-mouse-memoirs
      - font-mr-bedfort
      - font-mr-dafoe
      - font-mr-de-haviland
      - font-mrs-saint-delafield
      - font-mrs-sheppards
      - font-mystery-quest
      - font-neucha
      - font-neuton
      - font-new-rocker
      - font-news-cycle
      - font-niconne
      - font-nixie-one
      - font-nobile
      - font-nokora
      - font-norican
      - font-nosifer
      - font-nothing-you-could-do
      - font-noticia-text
      - font-nova-cut
      - font-nova-flat
      - font-nova-mono
      - font-nova-oval
      - font-nova-round
      - font-nova-script
      - font-nova-slim
      - font-nova-square
      - font-numans
      - font-nunito
      - font-odor-mean-chey
      - font-offside
      - font-old-standard-tt
      - font-oldenburg
      - font-oleo-script
      - font-oleo-script-swash-caps
      - font-open-sans
      - font-open-sans-condensed
      - font-oranienbaum
      - font-orbitron
      - font-oregano
      - font-orienta
      - font-original-surfer
      - font-oswald
      - font-over-the-rainbow
      - font-overlock
      - font-overlock-sc
      - font-ovo
      - font-oxygen
      - font-oxygen-mono
      - font-pacifico
      - font-paprika
      - font-parisienne
      - font-passero-one
      - font-passion-one
      - font-pathway-gothic-one
      - font-patrick-hand
      - font-patrick-hand-sc
      - font-patua-one
      - font-peralta
      - font-permanent-marker
      - font-petit-formal-script
      - font-petrona
      - font-philosopher
      - font-piedra
      - font-pinyon-script
      - font-pirata-one
      - font-plaster
      - font-play
      - font-playball
      - font-playfair-display
      - font-playfair-display-sc
      - font-podkova
      - font-poiret-one
      - font-poller-one
      - font-poly
      - font-pompiere
      - font-pontano-sans
      - font-port-lligat-sans
      - font-port-lligat-slab
      - font-prata
      - font-preahvihear
      - font-press-start2p
      - font-princess-sofia
      - font-prociono
      - font-prosto-one
      - font-puritan
      - font-purple-purse
      - font-quando
      - font-quantico
      - font-quattrocento
      - font-quattrocento-sans
      - font-questrial
      - font-quicksand
      - font-quintessential
      - font-qwigley
      - font-racing-sans-one
      - font-radley
      - font-raleway
      - font-raleway-dots
      - font-rambla
      - font-rammetto-one
      - font-ranchers
      - font-rancho
      - font-rationale
      - font-reenie-beanie
      - font-revalia
      - font-ribeye
      - font-ribeye-marrow
      - font-righteous
      - font-risque
      - font-roboto
      - font-roboto-condensed
      - font-roboto-mono
      - font-roboto-slab
      - font-rochester
      - font-rock-salt
      - font-rokkitt
      - font-romanesco
      - font-ropa-sans
      - font-rosario
      - font-rosarivo
      - font-rouge-script
      - font-ruda
      - font-rufina
      - font-ruge-boogie
      - font-ruluko
      - font-rum-raisin
      - font-ruslan-display
      - font-russo-one
      - font-ruthie
      - font-rye
      - font-sacramento
      - font-sail
      - font-salsa
      - font-sanchez
      - font-sancreek
      - font-sarina
      - font-satisfy
      - font-scada
      - font-schoolbell
      - font-seaweed-script
      - font-sevillana
      - font-seymour-one
      - font-shadows-into-light
      - font-shadows-into-light-two
      - font-shanti
      - font-share
      - font-share-tech
      - font-share-tech-mono
      - font-signika-negative
      - font-simonetta
      - font-sintony
      - font-skranji
      - font-sniglet
      - font-sorts-mill-goudy
      - font-stardos-stencil
      - font-stoke
      - font-syncopate
      - font-tangerine
      - font-tienne
      - font-tinos
      - font-titillium-web
      - font-trochut
      - font-unkempt
      - font-varela
      - font-volkhov
      - font-yanone-kaffeesatz
      - gimp
      - inkscape
      - r128x-gui
