---
- name: Update and upgrade Homebrew packages
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Upgrade Homebrew casks
  homebrew_cask: upgrade=yes

- name: Install pre-dependency casks
  homebrew_cask:
    state: present
    name:
      - java
      - xquartz

- name: Install machine brews
  homebrew:
    state: present
    name:
      - bind
      - dos2unix
      - lftp
      - nmap
      - p7zip
      - sox
      - unrar
      - wget

- name: Install machine casks
  homebrew_cask:
    state: present
    name:
      - android-file-transfer
      - android-platform-tools
      - android-studio
      - blender
      - emacs
      - fontforge
      - gimp
      - handbrake
      - inkscape-nightly
      - keepassxc
      - krita
      - libreoffice
      - nethackcocoa
      - nextcloud
      - obs
      - r128x-gui
      - scribus
      - transmission
      - vcv-rack
      - virtualbox
      - vlc
