---
- name: Update and upgrade Homebrew packages
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Install pre-dependency casks
  homebrew_cask:
    state: present
    name:
      - java
      - xquartz

- name: Install machine brews
  homebrew:
    state: present
    name:
      - dos2unix
      - lftp
      - nmap
      - p7zip
      - sox
      - wget

- name: Install machine casks
  homebrew_cask:
    state: present
    name:
      - emacs
      - gimp
      - inkscape
      - r128x-gui
