---
- name: Upgrade brews
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Upgrade casks
  homebrew_cask: upgrade=yes

- name: Install pre-dependency casks
  homebrew_cask:
    state: present
    name:
      - java
      - xquartz

- name: Install machine brews
  homebrew:
    state: present
    name:
      - aide
      - bind
      - dos2unix
      - figlet
      - lftp
      - nmap
      - p7zip
      - sox
      - unrar
      - wget

- name: Install machine casks
  homebrew_cask:
    state: present
    name:
      - emacs
      - homebrew/cask-fonts/font-hack
