---
- name: Copy the SSH public key
  copy: src=authorized_keys dest='{{ ansible_env.HOME }}/.ssh/authorized_keys'

- name: Copy the SSH configuration file
  copy: src=ssh_config dest='{{ ansible_env.HOME }}/.ssh/config'

- name: Copy the bash configuration file
  copy: src=bashrc dest='{{ ansible_env.HOME }}/.bashrc'

- name: Copy the shell login profile
  copy: src=profile dest='{{ ansible_env.HOME }}/.profile'

- name: Copy the Emacs configuration file
  copy: src=emacs dest='{{ ansible_env.HOME }}/.emacs'

- name: Copy the git configuration file
  copy: src=gitconfig dest='{{ ansible_env.HOME }}/.gitconfig'

- name: Copy the screen configuration file
  copy: src=screenrc dest='{{ ansible_env.HOME }}/.screenrc'

- include: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_system|lower }}.yml'
      skip: true

- include: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_pkg_mgr }}.yml'
      skip: true
