---
- include: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_system|lower }}.yml'
      skip: true

- include: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_pkg_mgr }}.yml'
      skip: true
