---
- name: Enable backports source
  become: yes
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present
    filename: backports

- name: Update and upgrade packages
  become: yes
  apt: update_cache=yes upgrade=dist

- name: Install zabbix-agent package
  become: yes
  apt: name=zabbix-agent state=present

- name: Install deborphan package
  become: yes
  apt: name=deborphan state=present

- name: Install screen package
  become: yes
  apt: name=screen state=present

- name: Sync bits
  git:
    repo: https://github.com/keeganquinn/bits.git
    dest: /home/keegan/public_html/bits
    version: master
