---
- name: Install nginx package
  become: yes
  apt: name=nginx state=present

- name: Copy nginx configuration
  become: yes
  copy:
    src: "config/{{ ansible_hostname }}/nginx/"
    dest: /etc/nginx/sites-enabled
  notify: restart nginx

- name: Copy SSL certificates
  become: yes
  copy:
    src: "config/{{ ansible_hostname }}/ssl/certs/"
    dest: /etc/ssl/certs
  notify: restart nginx

- name: Copy SSL keys
  become: yes
  copy:
    src: "config/{{ ansible_hostname }}/ssl/private/"
    dest: /etc/ssl/private
  notify: restart nginx
