---
- name: Install nginx package
  become: yes
  apt: name=nginx state=present

- name: Install certbot package
  become: yes
  apt: name=certbot state=present

- name: Generate Diffie-Hellman parameters for nginx
  become: yes
  command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
  notify: restart nginx

- name: Copy nginx virtual hosts
  become: yes
  copy:
    src: "config/{{ ansible_hostname }}/nginx/"
    dest: /etc/nginx/sites-enabled
  notify: restart nginx

- name: Copy SSL certificates
  become: yes
  copy:
    src: "config/{{ ansible_hostname }}/ssl/certs/"
    dest: /etc/ssl/certs
  notify: restart nginx

- name: Copy SSL keys
  become: yes
  copy:
    src: "config/{{ ansible_hostname }}/ssl/private/"
    dest: /etc/ssl/private
  notify: restart nginx
