---
- name: Install webserver packages
  become: yes
  apt:
    state: present
    name:
      - certbot
      - fail2ban
      - fcgiwrap
      - logcheck
      - nginx
      - rkhunter
      - zabbix-agent

- name: Copy fail2ban configuration file
  become: yes
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
  notify: restart fail2ban

- name: Copy rkhunter default file
  become: yes
  copy: src=rkhunter dest=/etc/default/rkhunter

- name: Generate Diffie-Hellman parameters for nginx
  become: yes
  command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
  notify: restart nginx

- name: Copy nginx logmap configuration
  become: yes
  copy:
    src: logmap.conf
    dest: /etc/nginx/conf.d
  notify: restart nginx

- name: Copy nginx virtual hosts
  become: yes
  copy:
    src: '{{ inventory_hostname }}/nginx/'
    dest: /etc/nginx/sites-available
  notify: restart nginx

- name: Enable nginx virtual hosts
  become: yes
  file:
    src: '/etc/nginx/sites-available/{{ item.path }}'
    dest: '/etc/nginx/sites-enabled/{{ item.path }}'
    state: link
    mode: 0644
    owner: root
    group: root
    force: true
  with_filetree:
    - '{{ inventory_hostname }}/nginx/'
  notify: restart nginx

- name: Create /etc/letsencrypt/renewal-hooks
  become: yes
  file:
    path: /etc/letsencrypt/renewal-hooks
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy certbot renewal hooks
  become: yes
  copy:
    src: deploy.hook
    dest: /etc/letsencrypt/renewal-hooks/deploy
    mode: 0755
  notify: renew certbot
