---
- name: Install certbot package
  become: yes
  apt: name=certbot state=present

- name: Install fcgiwrap package
  become: yes
  apt: name=fcgiwrap state=present

- name: Install nginx package
  become: yes
  apt: name=nginx state=present

- name: Generate Diffie-Hellman parameters for nginx
  become: yes
  command: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
  notify: restart nginx

- name: Copy nginx virtual hosts
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/nginx/'
    dest: /etc/nginx/sites-available
  notify: restart nginx

- name: Enable nginx virtual hosts
  become: yes
  file:
    src: '/etc/nginx/sites-available/{{ item.path }}'
    dest: '/etc/nginx/sites-enabled/{{ item.path }}'
    state: link
    mode: 0644
    owner: root
    group: root
    force: true
  with_filetree:
    - 'config/{{ ansible_hostname }}/nginx/'
  notify: restart nginx

- name: Copy SSL certificates
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/ssl/certs/'
    dest: /etc/ssl/certs
  notify: restart nginx

- name: Copy SSL keys
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/ssl/private/'
    dest: /etc/ssl/private
  notify: restart nginx

- name: Copy certbot renewal configuration
  become: yes
  copy:
    src: 'config/{{ ansible_hostname }}/letsencrypt/renewal/'
    dest: /etc/letsencrypt/renewal
  notify: renew certbot

- name: Create /etc/letsencrypt/renewal-hooks
  become: yes
  file:
    path: /etc/letsencrypt/renewal-hooks
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy certbot renewal hooks
  become: yes
  copy:
    src: deploy.hook
    dest: /etc/letsencrypt/renewal-hooks/deploy
    mode: 0755
  notify: renew certbot
