---
- name: reload sysctl
  become: yes
  command: sysctl -p

- name: restart dnsmasq
  become: yes
  service: name=dnsmasq state=restarted enabled=yes

- name: restart php-fpm
  become: yes
  service: name=php7.3-fpm state=restarted enabled=yes

- name: restart smbd
  become: yes
  service: name=smbd state=restarted enabled=yes

- name: restart vncserver-keegan
  become: yes
  service: name=vncserver-keegan state=restarted enabled=yes
