---
- name: reload sysctl
  become: yes
  command: sysctl -p

- name: restart dnsmasq
  become: yes
  service: name=dnsmasq state=restarted enabled=yes

- name: restart php-fpm
  become: yes
  service: name=php7.0-fpm state=restarted enabled=yes

- name: restart smbd
  become: yes
  service: name=smbd state=restarted enabled=yes

- name: restart shairport-sync
  become: yes
  service: name=shairport-sync state=restarted enabled=yes
